# 服务器端口配置
server:
  port: 8080

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myDatabase
    username: root
    password: He301634.  # 请替换为你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver

# 应用信息配置
#info:
#  app:
#    name: mangoframemaster
#    version: 1.0.0
