# 服务器端口配置
server:
  port: 8080
logging:
  level:
    com : debug
  file:
    path: ./logs # 配置日志打印目录,默认名称为:spring.log
    name: ./logs/SpringLogging.log # 配置日志打印目录和名称,和上面的path选一即可
# 数据源配置  zsw
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clouddo?useUnicode=true&characterEncoding=utf8
    username: root
    password: root  # 请替换为你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver

## 数据源配置 hlt
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/myDatabase?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: He301634.  # 请替换为你的数据库密码
#    driver-class-name: com.mysql.cj.jdbc.Driver
# 应用信息配置
#info:
#  app:
#    name: mangoframemaster
#    version: 1.0.0
